// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLDQ7Cjz390TsYoNPRLEiPbiO-FBftEvs',
    appId: '1:65007163557:web:d50d9847bae00fbbb1154c',
    messagingSenderId: '65007163557',
    projectId: 'gform-it363',
    authDomain: 'gform-it363.firebaseapp.com',
    storageBucket: 'gform-it363.appspot.com',
    measurementId: 'G-QPDEM5VT75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJbf3HcXANX335CyqUJBiHeGw0-ZyY75c',
    appId: '1:65007163557:android:a1ea3760cac032c6b1154c',
    messagingSenderId: '65007163557',
    projectId: 'gform-it363',
    storageBucket: 'gform-it363.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHy94JFRnw1tNlj6n_2us7rpU_CvqGbgI',
    appId: '1:65007163557:ios:81472c88186e2d35b1154c',
    messagingSenderId: '65007163557',
    projectId: 'gform-it363',
    storageBucket: 'gform-it363.appspot.com',
    iosBundleId: 'com.example.flutterGform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHy94JFRnw1tNlj6n_2us7rpU_CvqGbgI',
    appId: '1:65007163557:ios:77c3acfca470c15fb1154c',
    messagingSenderId: '65007163557',
    projectId: 'gform-it363',
    storageBucket: 'gform-it363.appspot.com',
    iosBundleId: 'com.example.flutterGform.RunnerTests',
  );
}
